# Generated by Django 2.2.6 on 2019-10-09 20:22

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.BooleanField(default=False, null=True)),
                ('SponsorWay', models.SmallIntegerField(default=1, null=True)),
                ('ActivityName', models.CharField(max_length=60, null=True)),
                ('ActivityPhoto', models.FileField(max_length=255, null=True, upload_to='')),
                ('ActivityDetails', django_mysql.models.JSONField(default=dict, null=True)),
                ('StartTime', models.DateTimeField(auto_now=True, null=True)),
                ('EndTime', models.DateTimeField(null=True)),
                ('ConditionType', models.PositiveSmallIntegerField(default=1, null=True)),
                ('ConditionInfo', models.PositiveIntegerField(default=1, null=True)),
                ('ConditionNum', models.PositiveIntegerField(default=0, null=True)),
                ('SponsorPhoneNumber', models.CharField(max_length=20, null=True)),
                ('SponsorNickName', models.CharField(max_length=40, null=True)),
                ('SponsorWechatNumber', models.CharField(max_length=255, null=True)),
                ('ParticipantAttention', models.BooleanField(default=False, null=True)),
                ('ShareJurisdiction', models.BooleanField(default=False, null=True)),
                ('AllowQuitOrNot', models.BooleanField(default=False, null=True)),
                ('InviateFriends', models.BooleanField(default=False, null=True)),
                ('InputCommandOrNot', models.BooleanField(default=False, null=True)),
                ('ParticipateWay', models.BooleanField(default=False, null=True)),
                ('WinnerList', models.BooleanField(default=False, null=True)),
                ('ParticipantDrawNumber', models.PositiveSmallIntegerField(default=1, null=True)),
                ('OfficialAccountsName', models.CharField(max_length=40, null=True)),
                ('KindOfAcitivity', models.SmallIntegerField(default=0, null=True)),
                ('ActivityEnd', models.BooleanField(default=False, null=True)),
                ('participate', models.ManyToManyField(related_name='participate', to='user.User')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor', to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrizePhoto', models.URLField(max_length=255, null=True)),
                ('PrizeName', models.CharField(max_length=60, null=True)),
                ('PrizeNumber', models.PositiveSmallIntegerField(default=1, null=True)),
                ('WinningProbability', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('activity', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_and_prize.Activity')),
            ],
        ),
    ]
