# Generated by Django 2.2.6 on 2019-10-15 17:11

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_and_prize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ActivityDetails',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True, verbose_name='活动介绍'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ActivityEnd',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='活动是否结束'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ActivityName',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='活动名称'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ActivityPhoto',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='uploadfile/%Y/%m/%d/', verbose_name='活动头图'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='AllowQuitOrNot',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否能退出活动（高级、公众号）'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ConditionInfo',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='存总人数'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ConditionNum',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='存现有人数'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ConditionType',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='开奖条件'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='EndTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='活动结束时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='InputCommandOrNot',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否输入指令才能参加活动（高级）'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='InviateFriends',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否能邀请好友（快速、高级）'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='KindOfAcitivity',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='活动奖品种类'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='OfficialAccountsName',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='需要关注的公众号名称'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ParticipantAttention',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='活动参与者关注（快速）'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ParticipantDrawNumber',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='参与者的抽奖次数（转盘）'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ParticipateWay',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='活动参与途径（公众号）'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ShareJurisdiction',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='活动能否分享（快速、高级）'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='SponsorNickName',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='活动创建人名称'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='SponsorPhoneNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='活动创建人电话号码'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='SponsorWay',
            field=models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='活动创建方式'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='SponsorWechatNumber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='活动创建人微信号'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='StartTime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='活动开始时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='WinnerList',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='显示中奖者名单（转盘）'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='certificate',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='活动创建人是否认证'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='participate',
            field=models.ManyToManyField(blank=True, related_name='participate', to='user.User'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='sponsor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor', to='user.User'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='PrizeName',
            field=models.CharField(max_length=60, null=True, verbose_name='奖品名称'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='PrizeNumber',
            field=models.PositiveSmallIntegerField(default=1, null=True, verbose_name='奖品数量'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='PrizePhoto',
            field=models.ImageField(max_length=255, null=True, upload_to='uploadfile/%Y/%m/%d/', verbose_name='奖品图片'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='WinningProbability',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True, verbose_name='中奖概率'),
        ),
    ]
