# Generated by Django 2.2.6 on 2019-10-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_and_prize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitearray',
            name='invite_num',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='活动创建方式'),
        ),
    ]
