# Generated by Django 2.2.6 on 2019-10-23 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('activity_and_prize', '0002_invitearray_invite_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='winner',
        ),
        migrations.AddField(
            model_name='prize',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='user.User', verbose_name='中奖者'),
        ),
    ]
