# Generated by Django 2.2.6 on 2019-10-23 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('activity_and_prize', '0003_auto_20191023_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prize',
            name='winner',
        ),
        migrations.CreateModel(
            name='PrizeWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_and_prize.Prize')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='user.User', verbose_name='中奖者')),
            ],
        ),
    ]
