# Generated by Django 2.2.6 on 2019-10-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CertificateWay', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='认证方式')),
                ('UnifiedSocialCreditCode', models.CharField(blank=True, max_length=18, null=True, verbose_name='统一社会信用代码')),
                ('LegalRepresentativeName', models.CharField(blank=True, max_length=100, null=True, verbose_name='法定代表人姓名')),
                ('OrganizationIdPhoto', models.ImageField(default='defaultId.png', max_length=400, null=True, upload_to='uploadfile/%Y/%m/%d/', verbose_name='组织证件照')),
                ('SponsorRealName', models.CharField(blank=True, max_length=20, null=True, verbose_name='个人认证者名字')),
                ('IdType', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='个人证件类型')),
                ('IdNumber', models.CharField(blank=True, max_length=18, null=True, verbose_name='个人证件号码')),
                ('PhoneNumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='个人手机号码')),
                ('IdPhotoPositive', models.ImageField(blank=True, max_length=400, null=True, upload_to='uploadfile/%Y/%m/%d/', verbose_name='个人证件正面')),
                ('IdPhotoNegative', models.ImageField(blank=True, max_length=400, null=True, upload_to='uploadfile/%Y/%m/%d/', verbose_name='个人证件反面')),
                ('OrganizationName', models.CharField(blank=True, max_length=200, null=True, verbose_name='组织名称')),
                ('check', models.BooleanField(default=False, verbose_name='是否已经检查')),
                ('pass_check', models.BooleanField(default=False, verbose_name='是否认证成功')),
            ],
        ),
    ]
