# Generated by Django 2.2.6 on 2019-10-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CertificateWay', models.SmallIntegerField(default=1, null=True)),
                ('UnifiedSocialCreditCode', models.CharField(max_length=18, null=True)),
                ('LegalRepresentativeName', models.CharField(max_length=100, null=True)),
                ('OrganizationIdPhoto', models.URLField(max_length=255, null=True)),
                ('SponsorRealName', models.CharField(max_length=20, null=True)),
                ('IdType', models.PositiveSmallIntegerField(default=1, null=True)),
                ('IdNumber', models.CharField(max_length=18, null=True)),
                ('PhoneNumber', models.CharField(max_length=20, null=True)),
                ('IdPhotoPositive', models.URLField(max_length=255, null=True)),
                ('IdPhotoNegative', models.URLField(max_length=255, null=True)),
                ('OrganizationName', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
