# Generated by Django 2.2.6 on 2019-10-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='IdPhotoNegative',
            field=models.URLField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='IdPhotoPositive',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
