# Generated by Django 2.2.6 on 2019-11-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='payment_order_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='支付订单号'),
        ),
    ]
