# Generated by Django 2.2.6 on 2019-11-05 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('certification', '0002_certification_payment_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='pay_check',
            field=models.BooleanField(default=False, verbose_name='是否已经支付'),
        ),
        migrations.AddField(
            model_name='certification',
            name='sign1',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='第一次签名'),
        ),
        migrations.AddField(
            model_name='certification',
            name='sign2',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='第二次签名'),
        ),
        migrations.AddField(
            model_name='certification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authenticator', to='user.User', verbose_name='创建者'),
        ),
    ]
