# Generated by Django 2.2.6 on 2019-11-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0003_auto_20191105_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='sign1',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='sign2',
        ),
    ]
