# Generated by Django 2.2.6 on 2019-10-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0003_auto_20191012_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='IdPhotoNegative',
            field=models.ImageField(max_length=400, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='certification',
            name='IdPhotoPositive',
            field=models.ImageField(max_length=400, null=True, upload_to=''),
        ),
    ]
