# Generated by Django 2.2.6 on 2019-11-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0004_auto_20191106_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='out_refund_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='退款单号'),
        ),
    ]
