# Generated by Django 2.2.6 on 2019-11-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0005_certification_out_refund_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='refund_check',
            field=models.BooleanField(default=True, verbose_name='是否已经退款'),
        ),
    ]
