# Generated by Django 2.2.6 on 2019-10-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0005_auto_20191014_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='pass_check',
            field=models.BooleanField(default=False, verbose_name='是否认证成功'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='CertificateWay',
            field=models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='认证方式'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='IdNumber',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='个人证件号码'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='IdPhotoNegative',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to='uploadfile/%Y/%m/%d/', verbose_name='个人证件反面'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='IdPhotoPositive',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to='uploadfile/%Y/%m/%d/', verbose_name='个人证件正面'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='IdType',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='个人证件类型'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='LegalRepresentativeName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='法定代表人姓名'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='OrganizationIdPhoto',
            field=models.ImageField(default='defaultId.png', max_length=400, null=True, upload_to='uploadfile/%Y/%m/%d/', verbose_name='组织证件照'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='OrganizationName',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='组织名称'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='个人手机号码'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='SponsorRealName',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='个人认证者名字'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='UnifiedSocialCreditCode',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='统一社会信用代码'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='check',
            field=models.BooleanField(default=False, verbose_name='是否已经检查'),
        ),
    ]
