# Generated by Django 2.2.6 on 2019-11-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0006_certification_refund_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='refund_check',
            field=models.BooleanField(default=False, verbose_name='是否已经退款'),
        ),
    ]
