# Generated by Django 2.2.6 on 2019-10-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OpenId', models.CharField(db_index=True, default='0', max_length=100, null=True)),
                ('UserName', models.CharField(max_length=40, null=True)),
                ('AvatarUrl', models.URLField(max_length=255, null=True)),
                ('gender', models.PositiveSmallIntegerField(default=0, null=True)),
                ('country', models.CharField(max_length=40, null=True)),
                ('province', models.CharField(max_length=40, null=True)),
                ('city', models.CharField(max_length=40, null=True)),
                ('language', models.CharField(max_length=40, null=True)),
                ('ContactName', models.CharField(max_length=60, null=True)),
                ('PhoneNumber', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('certificate', models.BooleanField(default=False, null=True)),
                ('CreateActivityNum', models.PositiveSmallIntegerField(default=0, null=True)),
                ('ParticipateActivityNum', models.PositiveSmallIntegerField(default=0, null=True)),
                ('WinNum', models.PositiveSmallIntegerField(default=0, null=True)),
            ],
        ),
    ]
