# Generated by Django 2.2.6 on 2019-10-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='CreateActivityNum',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ParticipateActivityNum',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='WinNum',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
