# Generated by Django 2.2.6 on 2019-10-04 08:24

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prizePhoto', models.URLField(max_length=255, null=True)),
                ('prizeName', models.CharField(max_length=60)),
                ('prizeNumber', models.PositiveSmallIntegerField(default=0)),
                ('winningProbability', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(db_index=True, default='0', max_length=100)),
                ('token', models.CharField(default='0', max_length=255)),
                ('username', models.CharField(max_length=40)),
                ('avatarUrl', models.URLField(max_length=255)),
                ('gender', models.PositiveSmallIntegerField(default=0)),
                ('country', models.CharField(max_length=40)),
                ('province', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('language', models.CharField(max_length=40)),
                ('contactName', models.CharField(max_length=60)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('address', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificateWay', models.SmallIntegerField(default=0)),
                ('unifiedSocialCreditCode', models.CharField(max_length=18)),
                ('legalRepresentativeName', models.CharField(max_length=100)),
                ('OrganizationIdPhoto', models.URLField(max_length=255)),
                ('sponsorRealName', models.CharField(max_length=20)),
                ('idType', models.PositiveSmallIntegerField(default=0)),
                ('idNumber', models.CharField(max_length=18)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('idPhotoPositive', models.URLField(max_length=255)),
                ('idPhotoNegative', models.URLField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckyDraw_1.User')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificateOrNot', models.BooleanField(default=False)),
                ('sponsorWay', models.SmallIntegerField(default=0)),
                ('activityName', models.CharField(max_length=60)),
                ('activityPhoto', models.URLField(max_length=255)),
                ('activityDetails', django_mysql.models.JSONField(default=dict)),
                ('startTime', models.DateField(null=True)),
                ('endTime', models.DateField(null=True)),
                ('conditionType', models.SmallIntegerField(default=0, null=True)),
                ('conditionInfo', models.SmallIntegerField(default=0)),
                ('sponsorPhoneNumber', models.CharField(max_length=20)),
                ('sponsorNickName', models.CharField(max_length=40)),
                ('sponsorWechatNumber', models.CharField(max_length=255)),
                ('participantAttention', models.BooleanField(default=False)),
                ('shareJurisdiction', models.BooleanField(default=False)),
                ('allowQuitOrNot', models.BooleanField(default=False)),
                ('inviateFriends', models.BooleanField(default=False)),
                ('inputCommandOrNot', models.BooleanField(default=False)),
                ('participateWay', models.BooleanField(default=False)),
                ('winnerList', models.BooleanField(default=False)),
                ('participantDrawNumber', models.PositiveSmallIntegerField(default=1)),
                ('participate', models.ManyToManyField(related_name='participate', to='luckyDraw_1.User')),
                ('prizeInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luckyDraw_1.Prize')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor', to='luckyDraw_1.User')),
            ],
        ),
    ]
