# Generated by Django 2.2.6 on 2019-10-06 11:49

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificateOrNot', models.BooleanField(default=False, null=True)),
                ('sponsorWay', models.SmallIntegerField(default=1, null=True)),
                ('activityName', models.CharField(max_length=60, null=True)),
                ('activityPhoto', models.FileField(max_length=255, null=True, upload_to='')),
                ('activityDetails', django_mysql.models.JSONField(default=dict, null=True)),
                ('startTime', models.DateField(null=True)),
                ('endTime', models.DateField(null=True)),
                ('conditionType', models.SmallIntegerField(default=1, null=True)),
                ('conditionInfo', models.SmallIntegerField(default=1, null=True)),
                ('sponsorPhoneNumber', models.CharField(max_length=20, null=True)),
                ('sponsorNickName', models.CharField(max_length=40, null=True)),
                ('sponsorWechatNumber', models.CharField(max_length=255, null=True)),
                ('participantAttention', models.BooleanField(default=False, null=True)),
                ('shareJurisdiction', models.BooleanField(default=False, null=True)),
                ('allowQuitOrNot', models.BooleanField(default=False, null=True)),
                ('inviateFriends', models.BooleanField(default=False, null=True)),
                ('inputCommandOrNot', models.BooleanField(default=False, null=True)),
                ('participateWay', models.BooleanField(default=False, null=True)),
                ('winnerList', models.BooleanField(default=False, null=True)),
                ('participantDrawNumber', models.PositiveSmallIntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificateWay', models.SmallIntegerField(default=1, null=True)),
                ('unifiedSocialCreditCode', models.CharField(max_length=18, null=True)),
                ('legalRepresentativeName', models.CharField(max_length=100, null=True)),
                ('OrganizationIdPhoto', models.URLField(max_length=255, null=True)),
                ('sponsorRealName', models.CharField(max_length=20, null=True)),
                ('idType', models.PositiveSmallIntegerField(default=1, null=True)),
                ('idNumber', models.CharField(max_length=18, null=True)),
                ('phoneNumber', models.CharField(max_length=20, null=True)),
                ('idPhotoPositive', models.URLField(max_length=255, null=True)),
                ('idPhotoNegative', models.URLField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(db_index=True, default='0', max_length=100, null=True)),
                ('username', models.CharField(max_length=40, null=True)),
                ('avatarUrl', models.URLField(max_length=255, null=True)),
                ('gender', models.PositiveSmallIntegerField(default=0, null=True)),
                ('country', models.CharField(max_length=40, null=True)),
                ('province', models.CharField(max_length=40, null=True)),
                ('city', models.CharField(max_length=40, null=True)),
                ('language', models.CharField(max_length=40, null=True)),
                ('contactName', models.CharField(max_length=60, null=True)),
                ('phoneNumber', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prizePhoto', models.URLField(max_length=255, null=True)),
                ('prizeName', models.CharField(max_length=60, null=True)),
                ('prizeNumber', models.PositiveSmallIntegerField(default=1, null=True)),
                ('winningProbability', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('activity', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='luckyDraw_1.Activity')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='participate',
            field=models.ManyToManyField(related_name='participate', to='luckyDraw_1.User'),
        ),
        migrations.AddField(
            model_name='activity',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor', to='luckyDraw_1.User'),
        ),
    ]
