# Generated by Django 2.2.6 on 2019-10-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckyDraw_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certificate',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
