# Generated by Django 2.2.6 on 2019-10-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luckyDraw_1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
