# Generated by Django 2.2.6 on 2019-10-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckyDraw_1', '0002_user_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='phoneNumber',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
