# Generated by Django 2.2.6 on 2019-10-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckyDraw_1', '0002_remove_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_key',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
