# Generated by Django 2.2.6 on 2019-10-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luckyDraw_1', '0003_user_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='session_key',
        ),
    ]
