# Generated by Django 2.2.6 on 2019-10-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckyDraw_1', '0003_activity_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='officialAccountsName',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='endTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='startTime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
