# Generated by Django 2.2.6 on 2019-10-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckyDraw_1', '0004_auto_20191007_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='kindOfAcitivity',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
